const FETCH_USERS = 'FETCH_USERS';
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
const PAGINATE_USERS = 'PAGINATE_USERS';
const FETCH_PAGINATED_USERS_SUCCESS = 'FETCH_PAGINATED_USERS_SUCCESS';

export {
  FETCH_USERS,
  FETCH_USERS_SUCCESS,
  FETCH_USERS_FAILED,
  PAGINATE_USERS,
  FETCH_PAGINATED_USERS_SUCCESS
};